apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "redmine.fullname" . }}-deployment
  labels:
    {{- include "redmine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redmine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
       labels:
        {{- include "redmine.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          env:
            - name: redmineUSER
              value: {{ .Values.db.redmineUSER | quote }}
            - name: dbhost
              value: {{ .Values.db.dbhost | quote }}
            - name: redminePASS
              value: {{ .Values.db.redminePASS | quote }}
            - name: redmineDB
              value: {{ .Values.db.redmineDB | quote }}



