---
- name: Install Java
  # hosts: all
  # hosts: workers, masters
  hosts: workers_all, masters_all
  #user: ubuntu
  # sudo: yes
  # gather_facts: false
  become: true

  tasks:
    - name: Install Java using Ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - openjdk-11-jdk
      tags:
        java

    - name: check if java instaled
      shell: which java
      changed_when: false
      register: result
      tags:
        java

    - name: print java-path
      debug:
        var: result.stdout
      tags:
        java

    - name: create /var/jenkins directory
      become: yes
      become_method: sudo
      # become_user: ubuntu
      remote_user: ubuntu
      file:
        path: /var/jenkins
        state: directory
        mode: 0755
      tags:
        java
  
    - name: Change /var/jenkins owner
      become: yes
      ansible.builtin.file:
        path: /var/jenkins
        state: directory
        recurse: yes
        owner: ubuntu
        group: ubuntu
      tags:
        java