---
- hosts: db
  become: yes
  become_method: sudo
  # become_user: ubuntu

  # roles:
  #   - docker
  #   - mysql

  roles:
    - docker
    - role: mysql
      vars:
        dir: './secret'
        # app_port: 5000
      tags: typeA

