---
- hosts: server13
  become: true
  vars_files:
    - ./vars.yml
  tasks:
    - name: install docker-compose
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-compose
    
    - name: Git Clone repo
      git:
        repo: {{ gitclone }}
        dest: {{ pathsrc }}
        version: {{ branch }}
        accept_hostkey: yes
        # key_file: /home/harry/.ssh/id_rsa
      # become_user: harry

    - name: —Åreate directory Compose
      file:
        path={{ pathdest }}
        mode=0755
        owner=root
        group=root
        state=directory

    - name: copy Docker Compose files
      copy:
        src: {{ pathsrc }}/task4/compose/{{ item }}
        dest: {{ pathdest }}/{{ item }}
      loop:
      - docker-compose.yml
      - secret

    # use files parameter to use multiple docker-compose.yml files
    - name: deploy Docker Compose stack
      docker_compose:
        project_src: {{ pathdest }}
        files:
        - docker-compose.yml
