replicaCount: 1

image:
  repository: phpmyadmin/phpmyadmin
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: NodePort
  port: 80
  nodePort: 30001
  targetPort: 80

db:
  port: 3306
# chartName is - IP service
  dbhost: 10.100.24.205
  pass: redmine_root
# login - root
# pass - above

# access to web my DB:
#   mysqlUser: internship
#   mysqlPassword: internship_s1

# livenessProbe:
#   path: 172.31.3.252

# ingress:
#   enabled: false
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
