apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "phpmyadmin.fullname" . }}-deployment
  labels:
    {{- include "phpmyadmin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "phpmyadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
       labels:
        {{- include "phpmyadmin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 80
          env:
            - name: PMA_PORT
              value: {{ .Values.db.port | quote }}
            - name: PMA_HOST
              value: {{ .Values.db.dbhost | quote }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.db.pass | quote }}


