---
- name: Install Docker
  hosts: monitor
  #user: ubuntu
  # sudo: yes
  # gather_facts: false
  become: true

  tasks:
    - name: install dependency
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
  
    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  
    - name: chech if docker is started
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: '0662'
      tags:
        - role

    # - name: init password jenkin
    #   shell: docker exec jenkins-server cat /var/jenkins_home/secrets/initialAdminPassword
    #   changed_when: false
    #   register: result

    # - name: print init password jenkins
    #   debug:
    #     var: result.stdout
    