replicaCount: 2

image:
  repository: ivoitukh/redmine
  pullPolicy: IfNotPresent
  tag: 8

service:
  type: NodePort
  port: 3000
  nodePort: 30002
  targetPort: 3000
  containerPort: 3000

db:
  redmineUSER: redmine
  dbhost: 10.100.24.205
  redminePASS: secret
  redmineDB: redmineDB
