replicaCount: 1

image:
  repository: ivoitukh/redmine
  pullPolicy: IfNotPresent
  tag: 10

service:
  type: NodePort
  port: 3000
  nodePort: 30002
  targetPort: 30002
  containerPort: 3000

db:
  redmineUSER: redmine
  dbhost: 10.100.86.177
  redminePASS: secret
  redmineDB: redmineDB
